RSGShared = RSGShared or {}
RSGShared.Items = {

    -- revolver
    weapon_revolver_cattleman              = { name = 'weapon_revolver_cattleman',              label = 'Cattleman Revolver',                weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman.png',              unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_cattleman_mexican      = { name = 'weapon_revolver_cattleman_mexican',      label = 'Cattleman Mexican Revolver',        weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman_mexican.png',      unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_doubleaction           = { name = 'weapon_revolver_doubleaction',           label = 'Double Action Revolver',            weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction.png',           unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_doubleaction_gambler   = { name = 'weapon_revolver_doubleaction_gambler',   label = 'Double Action Gambler Revolver',    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction_gambler.png',   unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_schofied               = { name = 'weapon_revolver_schofied',               label = 'Schofied Revolver',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_schofied.png',               unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_lemat                  = { name = 'weapon_revolver_lemat',                  label = 'Lemat Revolver',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_lemat.png',                  unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_navy                   = { name = 'weapon_revolver_navy',                   label = 'Navy Revolver',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_revolver_navy_crossover         = { name = 'weapon_revolver_navy_crossover',         label = 'Navy Crossover Revolver',           weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy_crossover.png',         unique = true, useable = false, description = 'Placeholder' },
    -- pistol
    weapon_pistol_volcanic                 = { name = 'weapon_pistol_volcanic',                 label = 'Volcanic Pistol',                   weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_volcanic.png',                 unique = true, useable = false, description = 'Placeholder' },
    weapon_pistol_m1899                    = { name = 'weapon_pistol_m1899',                    label = 'm1899 Pistol',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_m1899.png',                    unique = true, useable = false, description = 'Placeholder' },
    weapon_pistol_mauser                   = { name = 'weapon_pistol_mauser',                   label = 'Mauser Pistol',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_mauser.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_pistol_semiauto                 = { name = 'weapon_pistol_semiauto',                 label = 'Semi-Auto Pistol',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_semiauto.png',                 unique = true, useable = false, description = 'Placeholder' },
    -- repeater
    weapon_repeater_carbine                = { name = 'weapon_repeater_carbine',                label = 'Carbine Repeater',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_carbine.png',                unique = true, useable = false, description = 'Placeholder' },
    weapon_repeater_winchester             = { name = 'weapon_repeater_winchester',             label = 'Winchester Repeater',               weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_winchester.png',             unique = true, useable = false, description = 'Placeholder' },
    weapon_repeater_henry                  = { name = 'weapon_repeater_henry',                  label = 'Henry Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_henry.png',                  unique = true, useable = false, description = 'Placeholder' },
    weapon_repeater_evans                  = { name = 'weapon_repeater_evans',                  label = 'Evans Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_evans.png',                  unique = true, useable = false, description = 'Placeholder' },
    -- rifle
    weapon_rifle_varmint                   = { name = 'weapon_rifle_varmint',                   label = 'Varmint Rifle',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_rifle_varmint.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_rifle_springfield               = { name = 'weapon_rifle_springfield',               label = 'Springfield Rifle',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_rifle_springfield.png',               unique = true, useable = false, description = 'Placeholder' },
    weapon_rifle_boltaction                = { name = 'weapon_rifle_boltaction',                label = 'Boltaction Rifle',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_rifle_boltaction.png',                unique = true, useable = false, description = 'Placeholder' },
    weapon_rifle_elephant                  = { name = 'weapon_rifle_elephant',                  label = 'Elephant Rifle',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_rifle_elephant.png',                  unique = true, useable = false, description = 'Placeholder' },
    -- sniperrifle
    weapon_sniperrifle_rollingblock        = { name = 'weapon_sniperrifle_rollingblock',        label = 'Rollingblock Sniper Rifle',         weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock.png',        unique = true, useable = false, description = 'Placeholder' },
    weapon_sniperrifle_rollingblock_exotic = { name = 'weapon_sniperrifle_rollingblock_exotic', label = 'Rollingblock Exotic Sniper Rifle',  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock_exotic.png', unique = true, useable = false, description = 'Placeholder' },
    weapon_sniperrifle_carcano             = { name = 'weapon_sniperrifle_carcano',             label = 'Rollingblock Carcano Sniper Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_carcano.png',             unique = true, useable = false, description = 'Placeholder' },
    -- shotgun
    weapon_shotgun_doublebarrel            = { name = 'weapon_shotgun_doublebarrel',            label = 'Double Barrel Shotgun',             weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel.png',            unique = true, useable = false, description = 'Placeholder' },
    weapon_shotgun_doublebarrel_exotic     = { name = 'weapon_shotgun_doublebarrel_exotic',     label = 'Double Barrel Exotic Shotgun',      weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel_exotic.png',     unique = true, useable = false, description = 'Placeholder' },
    weapon_shotgun_sawedoff                = { name = 'weapon_shotgun_sawedoff',                label = 'Sawedoff Shotgun',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_sawedoff.png',                unique = true, useable = false, description = 'Placeholder' },
    weapon_shotgun_semiauto                = { name = 'weapon_shotgun_semiauto',                label = 'Semi-Auto Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_semiauto.png',                unique = true, useable = false, description = 'Placeholder' },
    weapon_shotgun_pump                    = { name = 'weapon_shotgun_pump',                    label = 'Pump Action Shotgun',               weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_pump.png',                    unique = true, useable = false, description = 'Placeholder' },
    weapon_shotgun_repeating               = { name = 'weapon_shotgun_repeating',               label = 'Repeating Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_repeating.png',               unique = true, useable = false, description = 'Placeholder' },
    -- bow
    weapon_bow                             = { name = 'weapon_bow',                             label = 'Sandard Bow',                       weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow.png',                             unique = true, useable = false, description = 'Placeholder' },
    weapon_bow_improved                    = { name = 'weapon_bow_improved',                    label = 'Improved Bow',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow_improved.png',                    unique = true, useable = false, description = 'Placeholder' },
    -- lasso
    weapon_lasso                           = { name = 'weapon_lasso',                           label = 'Sandard Lasso',                     weight = 1000, type = 'weapon', ammotype = nil,             image = 'weapon_lasso.png',                           unique = true, useable = false, description = 'Placeholder' },
    weapon_lasso_reinforced                = { name = 'weapon_lasso_reinforced',                label = 'Reinforced Lasso',                  weight = 1000, type = 'weapon', ammotype = nil,             image = 'weapon_lasso_reinforced.png',                unique = true, useable = false, description = 'Placeholder' },
    -- melee / knife
    weapon_melee_knife                     = { name = 'weapon_melee_knife',                     label = 'Sandard Knife',                     weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_knife.png',                     unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_knife_jawbone             = { name = 'weapon_melee_knife_jawbone',             label = 'Jawbon Knife',                      weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_knife_jawbone.png',             unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_knife_trader              = { name = 'weapon_melee_knife_trader',              label = 'Tader Knife',                       weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_knife_trader.png',              unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_knife_horror              = { name = 'weapon_melee_knife_horror',              label = 'Horror Knife',                      weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_knife_horror.png',              unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_knife_rustic              = { name = 'weapon_melee_knife_rustic',              label = 'Rustic Knife',                      weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_knife_rustic.png',              unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_machete                   = { name = 'weapon_melee_machete',                   label = 'Machete',                           weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_machete.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_machete_horror            = { name = 'weapon_melee_machete_horror',            label = 'Machete Horror',                    weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_machete_horror.png',            unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_machete_collector         = { name = 'weapon_melee_machete_collector',         label = 'Machete Collector',                 weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_machete_collector.png',         unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_torch                     = { name = 'weapon_melee_torch',                     label = 'Torch',                             weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_torch.png', unique = true,      useable = false, description = 'Placeholder' },
    -- held
    weapon_melee_davy_lantern              = { name = 'weapon_melee_davy_lantern',              label = 'Davy Lantern',                      weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_davy_lantern.png',              unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_lantern_halloween         = { name = 'weapon_melee_lantern_halloween',         label = 'Halloween Lantern',                 weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_lantern_halloween.png',         unique = true, useable = false, description = 'Placeholder' },
    weapon_kit_binoculars                  = { name = 'weapon_kit_binoculars',                  label = 'Binoculars',                        weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_kit_binoculars.png',                  unique = true, useable = false, description = 'Placeholder' },
    weapon_kit_binoculars_improved         = { name = 'weapon_kit_binoculars_improved',         label = 'Improved Binoculars',               weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_kit_binoculars_improved.png',         unique = true, useable = false, description = 'Placeholder' },
    weapon_kit_camera                      = { name = 'weapon_kit_camera',                      label = 'Camera',                            weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_kit_camera.png', unique = true,       useable = false, description = 'Placeholder' },
    weapon_kit_camera_advanced             = { name = 'weapon_kit_camera_advanced',             label = 'Advanced Camera',                   weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_kit_camera_advanced.png',             unique = true, useable = false, description = 'Placeholder' },
    weapon_kit_metal_detector              = { name = 'weapon_kit_metal_detector',              label = 'Metal Detector',                    weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_kit_metal_detector.png',              unique = true, useable = false, description = 'Placeholder' },
    -- trown
    weapon_melee_hatchet                   = { name = 'weapon_melee_hatchet',                   label = 'Hatchet',                           weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_hatchet.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_hatchet_hunter            = { name = 'weapon_melee_hatchet_hunter',            label = 'Hunter Hatchet',                    weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_hatchet_hunter.png',            unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_hatchet_double_bit        = { name = 'weapon_melee_hatchet_double_bit',        label = 'Double Bit Hatchet',                weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_hatchet_double_bit.png',        unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_molotov                  = { name = 'weapon_thrown_molotov',                  label = 'Molotov',                           weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_molotov.png',                  unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_tomahawk                 = { name = 'weapon_thrown_tomahawk',                 label = 'Tomahawk',                          weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_tomahawk.png',                 unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_tomahawk_ancient         = { name = 'weapon_thrown_tomahawk_ancient',         label = 'Tomahawk Ancient',                  weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_tomahawk_ancient.png',         unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_dynamite                 = { name = 'weapon_thrown_dynamite',                 label = 'Dynamite',                          weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_dynamite.png',                 unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_poisonbottle             = { name = 'weapon_thrown_poisonbottle',             label = 'Poison Bottle',                     weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_poisonbottle.png',             unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_throwing_knives          = { name = 'weapon_thrown_throwing_knives',          label = 'Throwing Kives',                    weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_throwing_knives.png',          unique = true, useable = false, description = 'Placeholder' },
    weapon_melee_cleaver                   = { name = 'weapon_melee_cleaver',                   label = 'Cleaver',                           weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_melee_cleaver.png',                   unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_bolas                    = { name = 'weapon_thrown_bolas',                    label = 'Balas',                             weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_bolas.png',                    unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_bolas_hawkmoth           = { name = 'weapon_thrown_bolas_hawkmoth',           label = 'Hawkmoth Balas',                    weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_bolas_hawkmoth.png',           unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_bolas_ironspiked         = { name = 'weapon_thrown_bolas_ironspiked',         label = 'Iron Spiked Balas',                 weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_bolas_ironspiked.png',         unique = true, useable = false, description = 'Placeholder' },
    weapon_thrown_bolas_intertwined        = { name = 'weapon_thrown_bolas_intertwined',        label = 'Intertwined Balas',                 weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_thrown_bolas_intertwined.png',        unique = true, useable = false, description = 'Placeholder' },
    -- fishing
    weapon_fishingrod                      = { name = 'weapon_fishingrod',                      label = 'Fishing Rod',                       weight = 1000, type = 'weapon', ammotype = nil,            image = 'weapon_fishingrod.png',                      unique = true, useable = false, description = 'Placeholder' },

    -- ammo
    ammo_revolver = { name = 'ammo_revolver', label = 'Revolver Ammo', weight = 100, type = 'item', image = 'ammo_revolver.png', unique = false, useable = true, shouldClose = true, description = 'Placeholder' },

}
